import{a as A,S as R,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="https://pixabay.com/api/",q="50784112-005c51f7743801558c0ea8079",f=15;async function p(t,r){const o=encodeURIComponent(t);try{return(await A.get(S,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:f}})).data}catch(i){throw console.error("Помилка під час отримання зображень:",i),i}}const g=document.querySelector(".js-gallery"),y=document.querySelector(".js-loader");let c=new R(".gallery a",{captionsData:"alt",captionDelay:250});function b(t){if(!Array.isArray(t)||t.length===0){c.refresh();return}const r=t.map(({webformatURL:o,largeImageURL:i,tags:e,likes:s,views:l,comments:E,downloads:w})=>`<li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${o}" alt="${e}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${s}</p>
            <p class="info-item"><b>Views</b> ${l}</p>
            <p class="info-item"><b>Comments</b> ${E}</p>
            <p class="info-item"><b>Downloads</b> ${w}</p>
          </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",r),c.refresh()}function I(){g.innerHTML="",c.refresh()}function L(){y.classList.add("is-visible")}function v(){y.classList.remove("is-visible")}const M=document.querySelector(".js-form"),h=document.querySelector('input[name="search-text"]'),d=document.querySelector(".js-load-more-btn");m();let n=1,u="";function P(){d.classList.remove("hidden")}function m(){d.classList.add("hidden")}M.addEventListener("submit",async t=>{t.preventDefault();const r=h.value.trim();if(r===""){a.error({title:"Error",message:"Будь ласка, введіть щось для пошуку!",position:"topRight"});return}u=r,n=1,m(),I(),L();try{const o=await p(u,n);if(o.hits.length===0)a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",titleColor:"#fff"});else{b(o.hits);const i=Math.ceil(o.totalHits/f);n<i?P():a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})}}catch(o){a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Помилка під час пошуку зображень:",o)}finally{v(),h.value=""}});d.addEventListener("click",async()=>{n+=1,m(),L();try{const t=await p(u,n);if(t.hits.length>0){b(t.hits);const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}const o=Math.ceil(t.totalHits/f);n<o?P():a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})}else a.info({message:"No more images found for this query.",position:"bottomRight"})}catch(t){a.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"}),console.error("Помилка під час завантаження додаткових зображень:",t)}finally{v()}});
//# sourceMappingURL=index.js.map
